### ISSUE TITLE
Afficher les dépôts d'une orga

### ISSUE THREAD

**Issue by AntoineAugusti** [bzg/codegouvfr#17]

**Comment by bzg** [comment]
L'idée est de pouvoir cliquer sur une organisation et que cela envoie vers la liste et n'affiche que les dépôts de cette organisation, c'est bien ça ?

Quid de `http://.../?orga=[nom_orga]` pour l'affichage une fois que [cette FR](https://github.com/bzg/codegouvfr/issues/14) sera implémentée ?

**Comment by AntoineAugusti** [comment]
> L'idée est de pouvoir cliquer sur une organisation et que cela envoie vers la liste et n'affiche que les dépôts de cette organisation, c'est bien ça ?
C'est bien ça.

L'implémentation proposée me semble OK
